apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: data-lake
type: Opaque
data:
  access-key: ZGF0YWxha2V1c2Vy  # base64 de "datalakeuser"
  secret-key: ZGF0YWxha2VwYXNzd29yZA==  # base64 de "datalakepassword"
