apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: data-lake
data:
  AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql://airflow:airflow@postgres:5432/airflow"
  AIRFLOW__WEBSERVER__WEB_SERVER_PORT: "8080"
